apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
type: Opaque
data:
{{ (.Files.Glob "env/credentials/*" ).AsSecrets | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data: {{ range $key, $value := .Values.environment }}
  {{ $key }}: {{ default "" $value | trim | b64enc  }} {{ end }}
