# Default values for customertoken.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
domain: kubetest.com
environments:
  ENVVAR1: 1
service:
  type: ClusterIP
  port: 80
ingress:
  enables: false
